### ISSUE TITLE
Test failure during test_pod_network_limits with JSONDecodeError

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/charm-kube-ovn#32]
Seen in https://github.com/charmed-kubernetes/charm-kube-ovn/runs/8211276552?check_suite_focus=true

```
Traceback (most recent call last):
  File "/opt/github-runner/_work/charm-kube-ovn/charm-kube-ovn/tests/integration/test_kube_ovn.py", line 87, in test_pod_network_limits
    egress_bw = await run_bandwidth_test(
  File "/opt/github-runner/_work/charm-kube-ovn/charm-kube-ovn/tests/integration/test_kube_ovn.py", line 379, in run_bandwidth_test
    _, sum_received = parse_iperf_result(stdout)
  File "/opt/github-runner/_work/charm-kube-ovn/charm-kube-ovn/tests/integration/test_kube_ovn.py", line 346, in parse_iperf_result
    result = json.loads(output)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by addyess** [comment]
If the iperf response can't be parsed, at least print in the test why
https://github.com/charmed-kubernetes/charm-kube-ovn/pull/34
