### ISSUE TITLE
Test failure during test_pod_netem_latency with IndexError

### ISSUE THREAD

**Issue by Cynerva** [charmed-kubernetes/charm-kube-ovn#33]
Seen in https://github.com/charmed-kubernetes/charm-kube-ovn/runs/8241528455?check_suite_focus=true

```
Traceback (most recent call last):
  File "/opt/github-runner/_work/charm-kube-ovn/charm-kube-ovn/tests/integration/test_kube_ovn.py", line 168, in test_pod_netem_latency
    average_latency = parse_ping_delay(stdout)
  File "/opt/github-runner/_work/charm-kube-ovn/charm-kube-ovn/tests/integration/test_kube_ovn.py", line 430, in parse_ping_delay
    average_delay = delay_stats.split("/")[1]
IndexError: list index out of range
```

**Comment by addyess** [comment]
If the ping response can't be parsed, at least print in the test why
https://github.com/charmed-kubernetes/charm-kube-ovn/pull/34
